-- V2: catálogos de grupo y detalle de enfermedad, con su semilla versionada.
--
-- La FK de detalle hacia grupo SÍ va: es interna al catálogo y la controlamos
-- nosotros. La que no va, y no puede ir, es la de ficha_medica hacia acá: las
-- fichas históricas traen códigos huérfanos y FR-028c los admite. Esa está
-- deliberadamente ausente de V1.
--
-- FR-010 —el detalle tiene que pertenecer al grupo elegido— se valida en el
-- servicio contra estas tablas, al escribir.

SET QUOTED_IDENTIFIER ON;

CREATE TABLE grupo_enfermedad (
    id          INT           NOT NULL,
    descripcion NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_grupo_enfermedad PRIMARY KEY (id)
);

CREATE TABLE detalle_enfermedad (
    id                  INT           NOT NULL,
    grupo_enfermedad_id INT           NOT NULL,
    descripcion         NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_detalle_enfermedad PRIMARY KEY (id),
    CONSTRAINT FK_detalle_grupo FOREIGN KEY (grupo_enfermedad_id)
        REFERENCES grupo_enfermedad (id)
);

-- SEMILLA
--
-- Los códigos son reales: salen del extracto del sistema de referencia y son
-- los 27 grupos y 85 detalles que las fichas usan de verdad. La relación
-- detalle -> grupo también es real, y está verificada: ningún detalle cuelga de
-- dos grupos distintos.
--
-- Las descripciones NO están. El extracto trae los códigos pero no el texto del
-- catálogo: su columna de texto es la observación clínica de cada ficha, no el
-- nombre del detalle. Ponerles un nombre inventado sería peor que dejarlas
-- marcadas: quedarían indistinguibles de un dato real y nadie las corregiría.
--
-- Entran en una V3 cuando llegue el export de las tablas de catálogo del sistema
-- de referencia. Hasta entonces la pantalla muestra el código, que es con lo que
-- el operario tipea igual (la selección es por código, no por nombre).
--
-- El catálogo solo contiene los códigos observados. Un código que no esté acá se
-- comporta como huérfano, que es exactamente lo que FR-028b manda mostrar tal
-- cual y sin descripción.

INSERT INTO grupo_enfermedad (id, descripcion) VALUES
    (100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (300, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (400, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (500, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (520, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (530, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (600, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (800, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (900, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1000, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1110, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1120, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1130, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1140, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1150, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1160, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1170, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1190, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1300, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1500, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1600, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1800, N'PENDIENTE DE EXPORT DEL CATÁLOGO');

INSERT INTO detalle_enfermedad (id, grupo_enfermedad_id, descripcion) VALUES
    (1001, 100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1002, 100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1003, 100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1004, 100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1005, 100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1006, 100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1008, 100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (2001, 200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (2002, 200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (2003, 200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (2005, 200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (2006, 200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (2007, 200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (2008, 200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (2009, 200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (3001, 300, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (3003, 300, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (3006, 300, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (3007, 300, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (4001, 400, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (4002, 400, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (4003, 400, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (4006, 400, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (5001, 500, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (5004, 500, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (5005, 500, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (5006, 500, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (5201, 520, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (5208, 520, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (5304, 530, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (5308, 530, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (6001, 600, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (7001, 700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (7002, 700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (7004, 700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (7005, 700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (7006, 700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (8003, 800, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (8004, 800, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (9004, 900, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (9007, 900, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (9010, 900, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (10001, 1000, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (10003, 1000, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (10004, 1000, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (10005, 1000, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11001, 1100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11002, 1100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11003, 1100, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11102, 1110, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11105, 1110, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11107, 1110, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11108, 1110, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11209, 1120, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11210, 1120, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11301, 1130, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11304, 1130, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11308, 1130, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11309, 1130, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11312, 1130, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11313, 1130, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11406, 1140, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11506, 1150, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11509, 1150, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11608, 1160, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11708, 1170, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11901, 1190, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11902, 1190, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11903, 1190, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11904, 1190, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11906, 1190, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11908, 1190, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (11909, 1190, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (12004, 1200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (12005, 1200, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (13002, 1300, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (13004, 1300, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (15001, 1500, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (16001, 1600, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (16004, 1600, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (16005, 1600, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1701, 1700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1702, 1700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (1703, 1700, N'PENDIENTE DE EXPORT DEL CATÁLOGO'),
    (18001, 1800, N'PENDIENTE DE EXPORT DEL CATÁLOGO');
